name: MK_QSVM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pip=23.2.1
  - pip:
    - qiskit==0.44.1
    - qiskit-aer==0.12.2
    - qiskit-machine-learning==0.6.0
    - dimod==0.12.8
    - umap-learn==0.5.3
    - plotly==5.16.1
    - kaleido==0.2.1
    - tqdm==4.66.1
    - psutil==5.9.5 